### ISSUE TITLE
Unable to run in ElectronJS

### ISSUE THREAD

**Issue by peterremote1980** [koltyakov/sp-pnp-node#13]
Hi
   If i put my code in electronJS, it has this error. Please help

```
>npm run start

> sharepoint-tray@1.0.0 start /Users/peter/workspace/sharepoint-tray
> electron .

Error: Unknown cipher
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:20)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:105:10)
    at Object.encrypt (/Users/peter/workspace/sharepoint-tray/node_modules/simple-encryptor/index.js:58:25)
    at Cpass.encode (/Users/peter/workspace/sharepoint-tray/node_modules/cpass/dist/Cpass.js:19:34)
    at Object.exports.convertAuthContextToSettings (/Users/peter/workspace/sharepoint-tray/node_modules/node-sp-auth-conf
ig/dist/utils/index.js:27:37)
    at /Users/peter/workspace/sharepoint-tray/node_modules/node-sp-auth-config/dist/utils/index.js:52:38
    at new Promise (<anonymous>)
    at Object.exports.saveConfigOnDisk (/Users/peter/workspace/sharepoint-tray/node_modules/node-sp-auth-config/dist/util
s/index.js:51:12)
    at AuthConfig.<anonymous> (/Users/peter/workspace/sharepoint-tray/node_modules/node-sp-auth-config/dist/index.js:83:4
4)
    at step (/Users/peter/workspace/sharepoint-tray/node_modules/node-sp-auth-config/dist/index.js:43:23)
    at Object.next (/Users/peter/workspace/sharepoint-tray/node_modules/node-sp-auth-config/dist/index.js:24:53)
    at fulfilled (/Users/peter/workspace/sharepoint-tray/node_modules/node-sp-auth-config/dist/index.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:749:11)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
```

**Comment by koltyakov** [comment]
The code must be executed on Electron backend, not in any case on a browsers frontend side.
A sample of usage with Electron can be found in this demo: https://github.com/koltyakov/spday-spb-2018-js-usecases/tree/master/src/06-Electron

The demo sample assumes that credentials are already at place and stored in private.json file. With the same success they can be passed from client-side part to backend-part of Electron application using a form. 

Make sure that backend logic uses headless mode and no interactive auth wizard inputs happen.

**Comment by peterremote1980** [comment]
Thanks, let me read your link first. I found something, if i downgrade electronjs from 4.1.3 to 3.0.4, it works again.

**Comment by Alebat** [comment]
I managed to solve this error with the OnDemandCredentials login strategy but I found another issue.

I am trying to implement the '**Factory example**' here [https://www.npmjs.com/package/sp-pnp-node](https://www.npmjs.com/package/sp-pnp-node), with **electron**.

Firstly I run the example choosing "On Demand" in the terminal menu. The organization form appeared, i checked the remember me checkbox, I logged in and the script ended with the 'Unknown cipher' error above.
The private config JSON file changed to the following:
```js
{
  "siteUrl": "https://company.sharepoint.com/sites/OurSite/",
  "strategy": "OnDemandCredentials",
  "ondemand": true
}
```

Then I run the proxy (sp-rest-proxy) with the same config file: it worked remembering the credentials I saved just before.

Finally I ran again the example and this time it gave me the following error:

```
[node-sp-auth]: reading auth data from C:\Users\uuu\AppData\Roaming\spauth\ondemand\https___company.sharepoint.com_sites_OurSite.data
SyntaxError: Unexpected token c in JSON at position 2
    at JSON.parse (<anonymous>)
    at OnDemand.getAuth (project\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\OnDemand.js:43:28)
    at Object.getAuth (project\node_modules\node-sp-auth\lib\src\index.js:8:76)
    at PnpNode.fetch (project\node_modules\sp-pnp-node\dist\PnpNode.js:40:27)
    at SPHttpClient.retry (project\node_modules\@pnp\sp\dist\sp.es5.umd.js:361:29)
    at project\node_modules\@pnp\sp\dist\sp.es5.umd.js:387:23
    at new Promise (<anonymous>)
    at SPHttpClient.fetchRaw (project\node_modules\@pnp\sp\dist\sp.es5.umd.js:379:20)
    at SPHttpClient.fetch (project\node_modules\@pnp\sp\dist\sp.es5.umd.js:327:25)
    at project\node_modules\@pnp\odata\dist\odata.es5.umd.js:395:28
    at new Promise (<anonymous>)
    at Function.PipelineMethods.send (project\node_modules\@pnp\odata\dist\odata.es5.umd.js:377:20)
    at descriptor.value (project\node_modules\@pnp\odata\dist\odata.es5.umd.js:309:31)
    at next (project\node_modules\@pnp\odata\dist\odata.es5.umd.js:264:38)
    at project\node_modules\@pnp\odata\dist\odata.es5.umd.js:309:80
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:749:11)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
```

The content of such file is a base64 blob starting with `64c...`, but `node-sp-auth` tries to parse it as a JSON.

I browsed the code and I found that in `project\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\OnDemand.js` the method `getAuth` expects a JSON with cookies in that file.

**Comment by Alebat** [comment]
The issue I reported in the post above is actually caused by the same problem.
The cypher type `aes256` is not recognized as valid using electron while it is using node.
I found that using `aes-256-cbc` instead solves the problem.
